DROP DATABASE IF EXISTS canteen;

CREATE DATABASE canteen;
USE canteen;

CREATE TABLE `用户` (
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`名称` VARCHAR(255) NOT NULL,
	`性别` VARCHAR(255) NOT NULL,
	`出生日期` DATE NOT NULL,
	`学工号` VARCHAR(255) NOT NULL UNIQUE,
	PRIMARY KEY(`id`)
);

CREATE TABLE `商户` (
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`名称` VARCHAR(255) NOT NULL,
	`地址` VARCHAR(255),
	`评分` NUMERIC,
	PRIMARY KEY(`id`)
);

CREATE TABLE `用户收藏商户` (
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`用户_id` INT NOT NULL,
	`商户_id` INT NOT NULL,
	PRIMARY KEY(`id`)
);

CREATE TABLE `菜品` (
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`名称` VARCHAR(255) NOT NULL,
	`是否主打菜` BOOLEAN NOT NULL,
	`描述` TEXT(65535),
	`价格` NUMERIC NOT NULL,
	`原价格` NUMERIC DEFAULT NULL,
	`图片编号` INT UNIQUE,
	`收藏量` INT,
	`在线销量` INT,
	`排队销量` INT,
	`类别_id` INT NOT NULL,
	`评分` NUMERIC,
	PRIMARY KEY(`id`)
);

CREATE TABLE `类别` (
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`名称` VARCHAR(255) NOT NULL UNIQUE,
	PRIMARY KEY(`id`)
);

CREATE TABLE `菜品属于商户` (
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`商户_id` INT NOT NULL,
	`菜品_id` INT NOT NULL,
	PRIMARY KEY(`id`)
);

CREATE TABLE `用户收藏菜品` (
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`用户_id` INT NOT NULL,
	`菜品_id` INT NOT NULL,
	PRIMARY KEY(`id`)
);

CREATE TABLE `菜品包含过敏原` (
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`菜品_id` INT NOT NULL,
	`过敏原_id` INT NOT NULL,
	PRIMARY KEY(`id`)
);

CREATE TABLE `过敏原` (
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`名称` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`id`)
);

CREATE TABLE `用户评价商户` (
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`用户_id` INT NOT NULL,
	`商户_id` INT NOT NULL,
	`评分` NUMERIC NOT NULL,
	`评价内容` TEXT(65535),
	PRIMARY KEY(`id`)
);

CREATE TABLE `用户评价菜品` (
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`用户_id` INT NOT NULL,
	`菜品_id` INT NOT NULL,
	`评分` NUMERIC NOT NULL,
	`评价内容` TEXT(65535),
	PRIMARY KEY(`id`)
);

CREATE TABLE `排队订单` (
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`创建时间` TIME NOT NULL,
	`是否完成` BOOLEAN NOT NULL,
	PRIMARY KEY(`id`)
);

CREATE TABLE `用户创建排队订单` (
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`用户_id` INT NOT NULL,
	`排队订单_id` INT NOT NULL,
	PRIMARY KEY(`id`)
);

CREATE TABLE `排队订单包含菜品` (
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`排队订单_id` INT NOT NULL,
	`菜品_id` INT NOT NULL,
	PRIMARY KEY(`id`)
);

CREATE TABLE `在线订单` (
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`创建时间` TIME NOT NULL,
	`是否完成` BOOLEAN NOT NULL,
	PRIMARY KEY(`id`)
);

CREATE TABLE `用户创建在线订单` (
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`用户_id` INT NOT NULL,
	`在线订单_id` INT NOT NULL,
	PRIMARY KEY(`id`)
);

CREATE TABLE `在线订单包含菜品` (
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`在线订单_id` INT NOT NULL,
	`菜品_id` INT NOT NULL,
	PRIMARY KEY(`id`)
);

CREATE TABLE `消息` (
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`内容` TEXT(65535),
	`用户_id` INT NOT NULL,
	PRIMARY KEY(`id`)
);

CREATE TABLE `菜品属于类别` (
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`菜品_id` INT NOT NULL,
	`类别_id` INT NOT NULL,
	PRIMARY KEY(`id`)
);

CREATE TABLE `预定` (
    `id` INT NOT NULL AUTO_INCREMENT UNIQUE,
    `用户_id` INT NOT NULL,
    `商户_id` INT NOT NULL,
    `时间` TIMESTAMP NOT NULL,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`用户_id`) REFERENCES `用户`(`id`),
    FOREIGN KEY (`商户_id`) REFERENCES `商户`(`id`)
);

ALTER TABLE `用户收藏商户`
ADD FOREIGN KEY(`用户_id`) REFERENCES `用户`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `用户收藏商户`
ADD FOREIGN KEY(`商户_id`) REFERENCES `商户`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `菜品属于商户`
ADD FOREIGN KEY(`商户_id`) REFERENCES `商户`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `菜品属于商户`
ADD FOREIGN KEY(`菜品_id`) REFERENCES `菜品`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `用户收藏菜品`
ADD FOREIGN KEY(`用户_id`) REFERENCES `用户`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `用户收藏菜品`
ADD FOREIGN KEY(`菜品_id`) REFERENCES `菜品`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `菜品包含过敏原`
ADD FOREIGN KEY(`菜品_id`) REFERENCES `菜品`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `菜品包含过敏原`
ADD FOREIGN KEY(`过敏原_id`) REFERENCES `过敏原`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `用户评价商户`
ADD FOREIGN KEY(`用户_id`) REFERENCES `用户`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `用户评价商户`
ADD FOREIGN KEY(`商户_id`) REFERENCES `商户`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `用户评价菜品`
ADD FOREIGN KEY(`用户_id`) REFERENCES `用户`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `用户评价菜品`
ADD FOREIGN KEY(`菜品_id`) REFERENCES `菜品`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `用户创建排队订单`
ADD FOREIGN KEY(`用户_id`) REFERENCES `用户`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `用户创建排队订单`
ADD FOREIGN KEY(`排队订单_id`) REFERENCES `排队订单`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `排队订单包含菜品`
ADD FOREIGN KEY(`排队订单_id`) REFERENCES `排队订单`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `排队订单包含菜品`
ADD FOREIGN KEY(`菜品_id`) REFERENCES `菜品`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `用户创建在线订单`
ADD FOREIGN KEY(`用户_id`) REFERENCES `用户`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `用户创建在线订单`
ADD FOREIGN KEY(`在线订单_id`) REFERENCES `在线订单`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `在线订单包含菜品`
ADD FOREIGN KEY(`在线订单_id`) REFERENCES `在线订单`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `在线订单包含菜品`
ADD FOREIGN KEY(`菜品_id`) REFERENCES `菜品`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `消息`
ADD FOREIGN KEY(`用户_id`) REFERENCES `用户`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `菜品属于类别`
ADD FOREIGN KEY(`类别_id`) REFERENCES `类别`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `菜品属于类别`
ADD FOREIGN KEY(`菜品_id`) REFERENCES `菜品`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;

